name-template: "auth-portal v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels: [ "feat", "feature" ]
  - title: "🐛 Fixes"
    labels: [ "fix", "bug" ]
  - title: "🧰 Maintenance"
    labels: [ "chore", "refactor", "docs", "ci" ]
change-template: "- $TITLE (#$NUMBER) @$AUTHOR"
version-resolver:
  major:
    labels: ["breaking", "major"]
  minor:
    labels: ["feat", "feature", "minor"]
  patch:
    labels: ["fix", "bug", "security", "patch", "chore", "dependencies"]
  default: patch
template: |
  ## Changes
  $CHANGES
